url: "https://open320neo.justsomeone.ch"
baseurl: "https://open320neo.justsomeone.ch"
defaults:
  - scope:
      path: ""
    values:
      layout: "main"
  - scope:
      path: "posts/"
    values:
      layout: "post"